### ISSUE TITLE
code problem

### ISSUE THREAD

**Issue by namenotexist** [talkingwallace/Neural-Graph-Collaborative-Filtering-pytorch#1]
there is something wrong in gnnlayer when you calculate interpart2

**Comment by talkingwallace** [comment]
It seems that there is a mistake in the arxiv paper, in equation (7). So the computation of user-item interactions in my code is wrong.....
I will fix it, sorry for the late reply.

**Comment by namenotexist** [comment]
the paper is right, only the calculation order in your code has some mistake,  change to below      
inter_feature = torch.sparse.mm(L2,features)
        inter_feature = torch.mul(inter_feature,features)
        inter_part2 = self.interActTransform(inter_feature)r has some problem.

**Comment by talkingwallace** [comment]
Yeah, you are right. I will fix it. Thanks a lot.
