### ISSUE TITLE
a question in buildLaplacianMat function

### ISSUE THREAD

**Issue by xiaoleiHou214** [talkingwallace/Neural-Graph-Collaborative-Filtering-pytorch#4]
hello，your code helped me a lot,but I hava some question for your code.In buildLaplacianMat function,you use the whole ML1K data to build the LaplacianMat include the test data rating,I think there should use the train dataset,am I wrong?

**Comment by talkingwallace** [comment]
yes, test data should not be included in the Mat. It's my mistake. Sorry for the late reply.

**Comment by xiaoleiHou214** [comment]
thanks a lot
